### ISSUE TITLE
Final checklist for project submission

### ISSUE THREAD

**Issue by cwickham** [ST541-Fall2020/statistical-lusardi-project-google-searches#9]
@statistical-lusardi here is a checklist of things to do before submitting your project, due Sunday Dec 6th at midnight. 

* [x] **Review project structure** 

    It's good time to review your file and folder organization.  Remember group files into folders based on their purpose, and both folder and file names should be self-explanatory.  Follow conventions where it makes sense (e.g. R function definitions in an `R/` folder, data in a `data/` folder).
    
    Double-check your reorganization doesn't break any code.  Searching for old file names and paths in RStudio using Edit -> Find in Files, can be a useful technique to uncover places you've referenced folders or files.  You should also check any .Rmd files Knit without error, and include a Knit .md version in the repo.

* [x] **Write your report**

    Consider **me** (Charlotte) the audience for your report.  I want to know what you set out to do, what you did, and what you learned.  But, you might also attempt to write this to be suitable for someone outside of the class (i.e. a potential employer).

    Consider this report a summary document. You will likely have other files in your project that document the technical details of the things you did to complete the project. It is OK to refer a reader of the report to other files in your repository, but the reader shouldn’t have to read anything else to understand the primary goals and results of your project.
    
    You can also use this report to address rubric items.  Make sure to point out anything you did to "Exceed Expectations".

    * [x] Your report should be less than 3 pages, including figures, but excluding references.
    * [x] A PDF, or HTML, version of the report should be included in your repository. 
  
&nbsp;    

* [x] **Update your repository README**

    When I'm grading I'll visit this first.
    Your repo README should include:
    * [x] Your name
    * [x] A title for your project
    * [x] A brief (2-5 sentence) description of the project
    * [x] Links to both the written report and (if applicable) presentation slides 
    * [x] Pointers to someone who wants to reproduce your work, e.g.:
        * required packages
        * locations of important code files, and any order they need to be run in,
        * the primary functions, and how should they be used
    
&nbsp;    

* [x] **Double-check your README**
    
    Make sure you visit your [repository homepage]( https://github.com/ST541-Fall2020/statistical-lusardi-project-google-searches), and scroll down to the README.  Check the README appears as it should, and click on any links to ensure they work.
    
* [x] **Submit your project on [canvas](https://canvas.oregonstate.edu/courses/1781180/assignments/8120989)**, by providing the URL of your project repository: https://github.com/ST541-Fall2020/statistical-lusardi-project-google-searches.

**Comment by statistical-lusardi** [comment]
Comments on how to use the functions are included in the commented code and utils as well
